#!/usr/bin/env python3

from spae_aes import SpaeCipher
import sys
import binascii

if (len(sys.argv) < 6) | (len(sys.argv) > 7):
    print("ERROR: need at least 5 arguments: operation,key,nonce,message,associatedData.\nOptional: verbose")
    exit()
op = sys.argv[1]
key = binascii.unhexlify(sys.argv[2])
nonce = binascii.unhexlify(sys.argv[3])
message = binascii.unhexlify(sys.argv[4])
associatedData = binascii.unhexlify(sys.argv[5])
verbose=False
if len(sys.argv) == 7:
    verbose=True

if verbose:
    print("SPAE-AES-%d"%(len(key)*8))
    print("key length:             %d bits"%(len(key)*8))
    print("message length:         %d bytes"%len(message))
    print("associated data length: %d bytes"%len(associatedData))
    print("key:                    ",end="");SpaeCipher.printBytesAsHex(key)
    print("nonce:                  ",end="");SpaeCipher.printBytesAsHex(nonce)
    print("message:                ",end="");SpaeCipher.printBytesAsHex(message)
    print("associated data:        ",end="");SpaeCipher.printBytesAsHex(associatedData)

if op in ['e','enc','encrypt']:
    out = SpaeCipher.SPAE_enc(key,nonce,message,associatedData)
elif op in ['d','dec','decreypt']:
    out = SpaeCipher.SPAE_dec(key,nonce,message,associatedData)
else:
    out = SpaeCipher.SPAE_enc(key,nonce,message,associatedData)
    SpaeCipher.SPAE_dec(key,nonce,out,associatedData)
SpaeCipher.printBytesAsHex(out)
